"""initial schema

Revision ID: 5eeb64fbc3b0
Revises: 
Create Date: 2026-04-22 16:44:41.238981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import scanner_orchestrator.db.models


# revision identifiers, used by Alembic.
revision: str = '5eeb64fbc3b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_profile',
    sa.Column('id', scanner_orchestrator.db.models.GUID(), nullable=False),
    sa.Column('camera_model', sa.String(length=128), nullable=False),
    sa.Column('lens_model', sa.String(length=128), nullable=False),
    sa.Column('fx', sa.Float(), nullable=False),
    sa.Column('fy', sa.Float(), nullable=False),
    sa.Column('cx', sa.Float(), nullable=False),
    sa.Column('cy', sa.Float(), nullable=False),
    sa.Column('dist_coeffs', sa.JSON(), nullable=False),
    sa.Column('profile_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_hash', name='uq_calibration_hash')
    )
    op.create_index(op.f('ix_calibration_profile_profile_hash'), 'calibration_profile', ['profile_hash'], unique=False)
    op.create_table('capture_preset',
    sa.Column('id', scanner_orchestrator.db.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('rings', sa.Integer(), nullable=False),
    sa.Column('angular_step_deg', sa.Integer(), nullable=False),
    sa.Column('focus_planes', sa.Integer(), nullable=False),
    sa.Column('stack_mode', sa.String(length=16), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('parent_id', scanner_orchestrator.db.models.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('angular_step_deg > 0 AND angular_step_deg <= 90', name='ck_angular_step'),
    sa.CheckConstraint('focus_planes >= 1', name='ck_focus_planes'),
    sa.CheckConstraint('rings >= 1 AND rings <= 10', name='ck_rings'),
    sa.ForeignKeyConstraint(['parent_id'], ['capture_preset.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_profile',
    sa.Column('id', scanner_orchestrator.db.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('formats', sa.JSON(), nullable=False),
    sa.Column('lod_levels', sa.Integer(), nullable=False),
    sa.Column('texture_resolution', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('lod_levels >= 1 AND lod_levels <= 5', name='ck_lod_levels'),
    sa.CheckConstraint('texture_resolution IN (1024, 2048, 4096, 8192)', name='ck_texture_resolution'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specimen',
    sa.Column('id', scanner_orchestrator.db.models.GUID(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('size_mm', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('pin_status', sa.String(length=32), nullable=False),
    sa.Column('taxonomy', sa.JSON(), nullable=True),
    sa.Column('collection_name', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specimen_external_id'), 'specimen', ['external_id'], unique=False)
    op.create_table('session',
    sa.Column('id', scanner_orchestrator.db.models.GUID(), nullable=False),
    sa.Column('specimen_id', scanner_orchestrator.db.models.GUID(), nullable=False),
    sa.Column('preset_id', scanner_orchestrator.db.models.GUID(), nullable=False),
    sa.Column('calibration_id', scanner_orchestrator.db.models.GUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('operator', sa.String(length=128), nullable=True),
    sa.Column('manifest_key', sa.String(length=512), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calibration_id'], ['calibration_profile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preset_id'], ['capture_preset.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['specimen_id'], ['specimen.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_created_at', 'session', ['created_at'], unique=False)
    op.create_index('ix_session_specimen_id', 'session', ['specimen_id'], unique=False)
    op.create_index('ix_session_status', 'session', ['status'], unique=False)
    op.create_table('job',
    sa.Column('id', scanner_orchestrator.db.models.GUID(), nullable=False),
    sa.Column('session_id', scanner_orchestrator.db.models.GUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('attempt >= 1', name='ck_job_attempt'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_session_type', 'job', ['session_id', 'type'], unique=False)
    op.create_index('ix_job_status', 'job', ['status'], unique=False)
    op.create_table('license_record',
    sa.Column('id', scanner_orchestrator.db.models.GUID(), nullable=False),
    sa.Column('session_id', scanner_orchestrator.db.models.GUID(), nullable=False),
    sa.Column('owner_name', sa.String(length=256), nullable=False),
    sa.Column('license_type', sa.String(length=32), nullable=False),
    sa.Column('consent_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id'),
    sa.UniqueConstraint('session_id', name='uq_license_session')
    )
    op.create_table('session_export_profile',
    sa.Column('session_id', scanner_orchestrator.db.models.GUID(), nullable=False),
    sa.Column('export_profile_id', scanner_orchestrator.db.models.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['export_profile_id'], ['export_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'export_profile_id')
    )
    op.create_table('asset',
    sa.Column('id', scanner_orchestrator.db.models.GUID(), nullable=False),
    sa.Column('session_id', scanner_orchestrator.db.models.GUID(), nullable=False),
    sa.Column('job_id', scanner_orchestrator.db.models.GUID(), nullable=True),
    sa.Column('bucket', sa.String(length=128), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_checksum', 'asset', ['checksum_sha256'], unique=False)
    op.create_index('ix_asset_session_type', 'asset', ['session_id', 'asset_type'], unique=False)
    op.create_table('qa_check',
    sa.Column('id', scanner_orchestrator.db.models.GUID(), nullable=False),
    sa.Column('session_id', scanner_orchestrator.db.models.GUID(), nullable=False),
    sa.Column('asset_id', scanner_orchestrator.db.models.GUID(), nullable=True),
    sa.Column('job_id', scanner_orchestrator.db.models.GUID(), nullable=True),
    sa.Column('check_type', sa.String(length=32), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qa_session_type', 'qa_check', ['session_id', 'check_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_qa_session_type', table_name='qa_check')
    op.drop_table('qa_check')
    op.drop_index('ix_asset_session_type', table_name='asset')
    op.drop_index('ix_asset_checksum', table_name='asset')
    op.drop_table('asset')
    op.drop_table('session_export_profile')
    op.drop_table('license_record')
    op.drop_index('ix_job_status', table_name='job')
    op.drop_index('ix_job_session_type', table_name='job')
    op.drop_table('job')
    op.drop_index('ix_session_status', table_name='session')
    op.drop_index('ix_session_specimen_id', table_name='session')
    op.drop_index('ix_session_created_at', table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_specimen_external_id'), table_name='specimen')
    op.drop_table('specimen')
    op.drop_table('export_profile')
    op.drop_table('capture_preset')
    op.drop_index(op.f('ix_calibration_profile_profile_hash'), table_name='calibration_profile')
    op.drop_table('calibration_profile')
    # ### end Alembic commands ###
